const words = [
    'mount', 'power', 'north', 'month', 'think',
    'kings', 'drink', 'marks', 'sport', 'bread',
    'drive', 'pride', 'grand', 'great', 'light',
    'moist', 'pears', 'found', 'beard', 'phone',
    'mixed', 'crowd', 'proud', 'spear', 'drone',
    'grape', 'thing', 'model', 'fresh', 'first',
    'stand', 'print', 'drain', 'panel', 'round',
    'basic', 'spicy', 'thumb', 'world', 'smart',
    'radio', 'store', 'solve', 'speak', 'vital',
    'rhino', 'trace', 'peach', 'solar', 'point',
    'sugar', 'frame', 'pause', 'shake', 'other',
    'watch', 'today', 'focus', 'movie', 'royal',
    'flair', 'plant', 'olive', 'story', 'train',
    'badge', 'metal', 'gamer', 'money', 'album',
    'depth', 'float', 'input', 'field', 'voice',
    'night', 'prize', 'enjoy', 'valid', 'equal',
    'dream', 'baker', 'count', 'study', 'lunch',
    'quick', 'honey', 'price', 'grace', 'cream',
    'reply', 'heart', 'diner', 'smile', 'build',
    'write', 'slide', 'union', 'lucky', 'house',
    'place', 'index', 'juicy', 'stage', 'clean',
    'ridge', 'vowel', 'thank', 'track', 'range',
    'brain', 'candy', 'layer', 'fluid', 'score',
    'sound', 'ocean', 'solid', 'relax', 'laugh',
    'earth', 'brave', 'guest', 'child', 'share',
    'pearl', 'large', 'plane', 'crown', 'beach',
    'trade', 'roast', 'party', 'touch', 'ready',
    'bonus', 'young', 'shape', 'short', 'space',
    'logic', 'towel', 'value', 'route', 'sharp',
    'pixel', 'audio', 'topic', 'tower', 'music'
]

export default words